### ISSUE TITLE
Roman[wdth,wght].ttf and Italic[wght].tff

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Cabin#2]
@moyogo
Assess status of current repo
All Roman masters are compatible with each other.
Italic masters are compatible.

Goal is two VF.ttf files
Roman with width (including Cond) + weight
Italic with weight.

**Comment by m4rc1e** [comment]
Just reviewed the files and I'm happy with them. Thank you. Could you send a pr to https://github.com/impallari/cabin thanks.
